### ISSUE TITLE
mgcb-editor not opening on macOS BigSur

### ISSUE THREAD

**Issue by thomasvidas** [MonoGame/MonoGame#7342]
Not expecting a fix for this until Big Sur is stable and not in beta, but figured I would open an issue to track just in case it is present in the full release of Big Sur. I am running Monogame 3.8.0.1641 and dotnet core 3.1.4.01

- Running `mgcb-editor` does nothing
- Opening the `.app` gives this error

<img width="261" alt="Screen Shot 2020-09-02 at 12 27 34 AM" src="https://user-images.githubusercontent.com/8182078/91932048-20188380-ecb3-11ea-81c9-d054a1ed6aab.png">

#### What version of MonoGame does the bug occur on:
- MonoGame (Editor) 3.8.0.1641

#### What operating system are you using:
- MacOS Big Sur (beta 5)

#### What MonoGame platform are you using:
- DesktopGL

**Comment by harry-cpp** [comment]
Fixed in: #7337

You can fix it manually by opening the .app as a folder and changing the name of `Contents/MacOS/mgcb-editor-mac` to `Contents/MacOS/MGCB Editor`.

**Comment by mannysz** [comment]
It did not solve the problem for me. I'm trying to fix on #7337 but I can't seem to get the develop branch to build using DotNet Core 3.1 on OS X Big Sur. Problems linking solutions to `mscorlib`.

```
BuildFlatpakTask.cs(33,10): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. [/Users/emanueldesouza/repo/MonoGame/Tools/MonoGame.Packaging.Flatpak/MonoGame.Packaging.Flatpak.csproj]
BuildFlatpakTask.cs(33,10): error CS0518: Predefined type 'System.Object' is not defined or imported [/Users/emanueldesouza/repo/MonoGame/Tools/MonoGame.Packaging.Flatpak/MonoGame.Packaging.Flatpak.csproj]
```

**Comment by carmonac** [comment]
This solution worked for Catalina but it's not working for Big Sur, should it be reopen this issue?

**Comment by cpt-max** [comment]
I built [this version here](https://www.dropbox.com/s/mjp2lopww4cbnlu/MGCB%20Editor.app.zip?dl=1). It works for me on M1.
More details: https://github.com/MonoGame/MonoGame/issues/7513#issuecomment-1017085637

**Comment by zrezke** [comment]
Installing x64 version of dotnet solved it for me, I found this solution here: https://community.monogame.net/t/mgcb-not-launching-on-macos-m1/17948/3
Link to download: [dotnet 6](https://dotnet.microsoft.com/en-us/download/dotnet/6.0)
